var tb = "text"
var cb = "checkbox"
//hydraulic equipment hazard data
var allHydraulic = [
    {text:"Equipment Description, what is it used for?",input:tb},
    {text:"Size and location of the room",input:tb},
    {text:"Construction and fire resistance, at least 1 hour, check fire doors",input:tb},
    {text:"Type of fluid and propeties flash point - petroeum based, water based, less hazardous",input:tb},
    {text:"Operating pressure and temperature of the fluid",input:tb},
    {text:"Containment or Drainage for the reservoir",input:cb},
    {text:"Reservoir Size",input:tb},
    {text:"Fire protection - if at least one manual or automatic interlock use 0.18/2500 at least If no interlocks use .28/3000",input:tb},
    {text:"Low reservoir level interlocks",input:cb},
    {text:"Flame or heat detection above pumps, filters and reservoir",input:cb},
    {text:"Interlocked to sprinkler system",input:cb},
    {text:"Manual e-stop at least 40ft from equipment",input:cb},
    {text:"At least one manual or automatic interlock",input:cb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
];
//storage Hazard data
var allStorage =[
    {text:"Size of the area sq ft", input:tb},
    {text:"Ceiling height and slope peak, eave and distance. should be less than 16%", input:tb},
    {text:"construction and fire resistance of the area", input:tb},
    {text:"Metal Halide lamps", input:cb},
    {text:"Lamps fixtures with containment barriers", input:cb},
    {text:"Turn off at least once a week for a minimum of 15 min", input:cb},
    {text:"Commodity description", input:tb},
    {text:"Commodity Encapsulated",input:cb},
    {text:"Open top containers",input:cb},
    {text:"Plastic Pallets",input:cb},
    {text:"Wood Pallets",input:cb},
    {text:"Solid Pile",input:cb},
    {text:"Palletized",input:cb},
    {text:"Rack Storage",input:cb},
    {text:"Shelf Storage",input:cb},
    {text:"SRR",input:cb},
    {text:"DRR",input:cb},
    {text:"MRR",input:cb},
    {text:"Storage height",input:tb},
    {text:"Number of racks and length",input:tb},
    {text:"Aisle width",input:tb},
    {text:"Type of shelving open, solid, wire mesh etc",input:tb},
    {text:"6 inch trasnverse flue between loads",input:cb},
    {text:"6 inch longitudinal flue between racks",input:cb},
    {text:"Pallet Size",input:tb},
    {text:"Fire protection type wet, preaction, foam, dry",input:tb},
    {text:"Design Density",input:tb},
    {text:"Sprinkler manufacturer, type, k factor, and temperature rating",input:tb},
    {text:"IRAS number of lines per rack, design, # heads per level, spacing, k factor, tempreature rating, manufacturer and demands",input:tb},
    {text:"CMDA obstructions over 4ft",input:cb},
    {text:"Sprinklers under obstructions",input:cb},
    {text:"Obstruction details, width horizontal distance to obstruction, vertical distance",input:tb},
    {text:"HVLS fans",input:cb},
    {text:"HVLS fans vertical clearance from fan to deflector minimum 3ft",input:cb},
    {text:"HVLS interlocked to waterflow or smoke det.",input:cb},
    {text:"Additional comments",input:tb},
    {text:"Final Output",input:tb}
];
var allGenerator = [
    {text:"Manufacturer and Size KW",input:tb},
    {text:"Size and location room",input:tb},
    {text:"Construction and fire resistance, at least 1 hour, check fire doors",input:tb},
    {text:"The generator has a containment wall",input:cb},
    {text:"The generator has a containment curb",input:cb},
    {text:"The generator has a dike or drainage",input:cb},
    {text:"The generator has a secondary containment tank",input:cb},
    {text:"The generator room has sprinklers",input:cb},
    {text:"The sprinklers have a minimum 0.30/2500",input:cb},
    {text:"The generator is diesel",input:cb},
    {text:"The generator is natural gas",input:cb},
    {text:"Fuel tank location (inside or outside) and size",input:tb},
    {text:"Diesel tank has secondary containment",input:cb},
    {text:"Diesel tank is double walled",input:cb},
    {text:"Leak detection interlocked with pumps",input:cb},
    {text:"System shuts down on pipe break",input:cb},
    {text:"Pumps interlocked upon suppression activation",input:cb},
    {text:"Manual or automatic shutoffs",input:cb},
    {text:"LEL detection",input:cb},
    {text:"Additional Comments like mainteance weekly excercised, full load test Generator Alarms, tank alarms, smoke detectors in the room etc",input:tb},
    {text:"Final Output",input:tb}
]