var tb = "text"
var cb = "checkbox"
//hydraulic equipment hazard data
var allHydraulic = [
    {text:"Equipment Description, what is it used for?",input:tb},
    {text:"Size and location of the room",input:tb},
    {text:"Construction and fire resistance, at least 1 hour, check fire doors",input:tb},
    {text:"Type of fluid and propeties flash point - petroeum based, water based, less hazardous",input:tb},
    {text:"Operating pressure and temperature of the fluid",input:tb},
    {text:"Containment or Drainage for the reservoir",input:cb},
    {text:"Reservoir Size",input:tb},
    {text:"Fire protection - if at least one manual or automatic interlock use 0.18/2500 at least If no interlocks use .28/3000",input:tb},
    {text:"Low reservoir level interlocks",input:cb},
    {text:"Flame or heat detection above pumps, filters and reservoir",input:cb},
    {text:"Interlocked to sprinkler system",input:cb},
    {text:"Manual e-stop at least 40ft from equipment",input:cb},
    {text:"At least one manual or automatic interlock",input:cb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
];
//storage Hazard data
var allStorage =[
    {text:"Size of the area sq ft", input:tb},
    {text:"Ceiling height and slope peak, eave and distance. should be less than 16%", input:tb},
    {text:"construction and fire resistance of the area", input:tb},
    {text:"Metal Halide lamps", input:cb},
    {text:"Lamps fixtures with containment barriers", input:cb},
    {text:"Turn off at least once a week for a minimum of 15 min", input:cb},
    {text:"Commodity description", input:tb},
    {text:"Commodity Encapsulated",input:cb},
    {text:"Open top containers",input:cb},
    {text:"Plastic Pallets",input:cb},
    {text:"Wood Pallets",input:cb},
    {text:"Solid Pile",input:cb},
    {text:"Palletized",input:cb},
    {text:"Rack Storage",input:cb},
    {text:"Shelf Storage",input:cb},
    {text:"SRR",input:cb},
    {text:"DRR",input:cb},
    {text:"MRR",input:cb},
    {text:"Storage height",input:tb},
    {text:"Number of racks and length",input:tb},
    {text:"Aisle width",input:tb},
    {text:"Type of shelving open, solid, wire mesh etc",input:tb},
    {text:"6 inch trasnverse flue between loads",input:cb},
    {text:"6 inch longitudinal flue between racks",input:cb},
    {text:"Pallet Size",input:tb},
    {text:"Fire protection type wet, preaction, foam, dry",input:tb},
    {text:"Design Density",input:tb},
    {text:"Sprinkler manufacturer, type, k factor, and temperature rating",input:tb},
    {text:"IRAS number of lines per rack, design, # heads per level, spacing, k factor, tempreature rating, manufacturer and demands",input:tb},
    {text:"CMDA obstructions over 4ft",input:cb},
    {text:"Sprinklers under obstructions",input:cb},
    {text:"Obstruction details, width horizontal distance to obstruction, vertical distance",input:tb},
    {text:"HVLS fans",input:cb},
    {text:"HVLS fans vertical clearance from fan to deflector minimum 3ft",input:cb},
    {text:"HVLS interlocked to waterflow or smoke det.",input:cb},
    {text:"Additional comments",input:tb},
    {text:"Final Output",input:tb}
];
var allGenerator = [
    {text:"Manufacturer and Size KW",input:tb},
    {text:"Size and location room",input:tb},
    {text:"Construction and fire resistance, at least 1 hour, check fire doors",input:tb},
    {text:"The generator has a containment wall",input:cb},
    {text:"The generator has a containment curb",input:cb},
    {text:"The generator has a dike or drainage",input:cb},
    {text:"The generator has a secondary containment tank",input:cb},
    {text:"The generator room has sprinklers",input:cb},
    {text:"The sprinklers have a minimum 0.30/2500",input:cb},
    {text:"The generator is diesel",input:cb},
    {text:"The generator is natural gas",input:cb},
    {text:"Fuel tank location (inside or outside) and size",input:tb},
    {text:"Diesel tank has secondary containment",input:cb},
    {text:"Diesel tank is double walled",input:cb},
    {text:"Leak detection interlocked with pumps",input:cb},
    {text:"System shuts down on pipe break",input:cb},
    {text:"Pumps interlocked upon suppression activation",input:cb},
    {text:"Manual or automatic shutoffs",input:cb},
    {text:"LEL detection",input:cb},
    {text:"Additional Comments like mainteance weekly excercised, full load test Generator Alarms, tank alarms, smoke detectors in the room etc",input:tb},
    {text:"Final Output",input:tb}
];
var allFlammableLiquids = [
    {text:"Size and Location of Room (dimensions, area)",input:tb},
    {text:"Ceiling Height",input:tb},
    {text:"Construction and fire resistance rating of room (150 sq.ft. – 1 hour; <=500 sq.ft. – 2 hours; 30-9.9.1: if >500 must be a warehouse)",input:tb},
    {text:"Classification of liquids, Container sizes and Total Quantities (see 30, 9.7 for MAQs)",input:tb},
    {text:"Explosion Protection (Venting required if Class IA liquids are stored in containers larger than 1 gal (4 L), except for rooms totally enclosed in a building (30, 9.16.1)",input:tb},
    {text:"Storage arrangement (Note below grade storage of Class I is not allowed – 30,9.3.6)",input:tb},
    {text:"Containment - min 4 inch curb see 30, 9.13 and Fig. 16.8.1",input:cb},
    {text:"Drainage",input:cb},
    {text:"Sprinklers at the ceiling",input:cb},
    {text:"Sprinkler design, type (CMDA, ESFR), wet, dry, k factor, rating",input:tb},
    {text:"Dispensing done in the room",input:cb},
    {text:"Gravity Natural supply ventilation within 12 inches floor",input:cb},
    {text:"Gravity Natural exahust ventilation within 12 inches floor",input:cb},
    {text:"Continious Mechanial exahust ventilation within 12 inches floor",input:cb},
    {text:"Continious Mechanial supply ventilation within 12 inches floor",input:cb},
    {text:"Electrical Rated equipment class 1 div 2 if class I liquids present",input:cb},
    {text:"Lower Explosive detection system",input:cb},
    {text:"Bonding",input:cb},
    {text:"Grounding",input:cb},
    {text:"Deadman valves for dispensing",input:cb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
];
var allBoiler = [
    {text:"Water Tube",input:cb},
    {text:"Fire Tube",input:cb},
    {text:"Manufacturer",input:tb},
    {text:"Size and location of the room",input:tb},
    {text:"Construction and fire resistance rating of room - look doors",input:tb},
    {text:"Room Fire Protection - Sprinklers, smoke detectors, extinguishers",input:tb},
    {text:"Burner Size (Btu/hr)",input:tb},
    {text:"low-water cutoff switch and Alarm",input:cb},
    {text:"Manual Shutoff Valve before",input:cb},
    {text:"Pressure regulator before",input:cb},
    {text:"Pressure relief valve before",input:cb},
    {text:"Low Gas Pressure Switch",input:cb},
    {text:"SSOV before",input:cb},
    {text:"Atmospheric Vent Valve",input:cb},
    {text:"SSOV after",input:cb},
    {text:"Manual shutoff valve after",input:cb},
    {text:"High pressure switch",input:cb},
    {text:"Leak test valves between double block and bleed and after second SSOV",input:cb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
];
var allFiredEquipment = [
    {text:"Description of Process What is being heated, etc",input:tb},
    {text:"Oil fuel",input:cb},
    {text:"Gas fuel",input:cb},
    {text:"Direct fired",input:cb},
    {text:"Indirect fired",input:cb},
    {text:"Burner Size (Btu/hr)",input:tb},
    {text:"Manual Shutoff Valve before",input:cb},
    {text:"Pressure regulator before",input:cb},
    {text:"Pressure relief valve before",input:cb},
    {text:"Low Gas Pressure Switch",input:cb},
    {text:"SSOV before",input:cb},
    {text:"Atmospheric Vent Valve",input:cb},
    {text:"SSOV after",input:cb},
    {text:"Manual shutoff valve after",input:cb},
    {text:"High pressure switch",input:cb},
    {text:"Leak test valves between double block and bleed and after second SSOV",input:cb},
    {text:"Explosion Venting - Explosion venting required for direct fuel-fired furnaces and furnaces that contain flammable liquids, gases, or combustible dusts",input:tb},
    {text:"High Temperature Interlocks",input:cb},
    {text:"LEL detection",input:cb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
];
var allFlammableGases = [
    {text:"Refer to NFPA 55 for additional requirements for bulk hydrogen, pyrophorics and ethylene oxide; Does not apply to laboratories - NFPA 45, LPG – NFPA 58, LNG – NFPA 59A, medical gas systems – NFPA 99 or closed cycle refrigeration systems ----Size and Location of Room/Storage area (Inside/outside, dimensions, area)",input:tb},
    {text:"Category/type of gases, Container sizes and Total Quantities - standard cubic feet",input:tb},
    {text:"Incompatible Material Segregated Flammable, oxidizing, corrosive, toxic and pyrophoric gases must be separated from each other by a noncombustible barrier of ½ hour fire resistance or separated by 20 ft.",input:tb},
    {text:"Cylinders/containers/tanks secured with valve-protective caps in place - required if not empty ",input:cb},
    {text:"Storage containers/cylinders/tanks physically protected from vehicular damage (e.g., guard posts/bollards)",input:cb},
    {text:"Storage area free of Combustibles",input:cb},
    {text:"Construction and fire resistance rating of room",input:tb},
    {text:"Mechanical exhaust ventilation or fixed natural ventilation required",input:cb},
    {text:"Explosion Protection ",input:cb},
    {text:"Fire Protection Systems - System type, design demand, sprinkler type, temperature rating",input:tb},
    {text:"Piping Systems Emergency shutoff valves required at the point of use",input:cb},
    {text:"Piping Systems Emergency shutoff valves required at the tank, cylinder or bulk source",input:cb},
    {text:"Piping Systems Emergency shutoff valves required at the point the system enters the building",input:cb},
    {text:"If system piping operates at over 15 psi, leak detection with emergency shutoff or excess flow control is required",input:cb},
    {text:"Continuous Gas Detection - Required when dispensing ethylene oxide",input:cb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
];
var allPropane = [
    {text:"Refer to NFPA 55 for additional requirements for bulk hydrogen, pyrophorics and ethylene oxide; Does not apply to laboratories - NFPA 45, LNG – NFPA 59A, medical gas systems – NFPA 99 or closed cycle refrigeration systems ----Size and Location of Room/Storage area (Inside/outside, dimensions, area)",input:tb},
    {text:"Category/type of gases, Container sizes and Total Quantities - standard cubic feet",input:tb},
    {text:"Incompatible Material Segregated Flammable, oxidizing, corrosive, toxic and pyrophoric gases must be separated from each other by a noncombustible barrier of ½ hour fire resistance or separated by 20 ft.",input:tb},
    {text:"Cylinders/containers/tanks secured with valve-protective caps in place - required if not empty ",input:cb},
    {text:"Storage containers/cylinders/tanks physically protected from vehicular damage (e.g., guard posts/bollards)",input:cb},
    {text:"Storage area free of Combustibles",input:cb},
    {text:"Construction and fire resistance rating of room",input:tb},
    {text:"Mechanical exhaust ventilation or fixed natural ventilation required",input:cb},
    {text:"Explosion Protection ",input:cb},
    {text:"Fire Protection Systems - System type, design demand, sprinkler type, temperature rating",input:tb},
    {text:"Piping Systems Emergency shutoff valves required at the point of use",input:cb},
    {text:"Piping Systems Emergency shutoff valves required at the tank, cylinder or bulk source",input:cb},
    {text:"Piping Systems Emergency shutoff valves required at the point the system enters the building",input:cb},
    {text:"If system piping operates at over 15 psi, leak detection with emergency shutoff or excess flow control is required",input:cb},
    {text:"Continuous Gas Detection - Required when dispensing ethylene oxide",input:cb},    
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
];
var allAmmonia = [
    {text:"System Description (also indicate if direct or Indirect)",input:tb},
    {text:"Size and Location of Machine Room(dimensions, area)",input:tb},
    {text:"Construction and fire resistance rating of room ",input:tb},
    {text:"Quantity of Ammonia in System",input:tb},
    {text:"Incompatible Material Segregated - Flammable, oxidizing, corrosive, toxic and pyrophoric gases",input:cb},
    {text:"Vapor Detection, Monitoring and Alarm Systems for Refrigerated Spaces with Evaporators",input:cb},
    {text:"Vapor Detection, Monitoring and Alarm Systems for Machine Room",input:cb},
    {text:"Machine Room Alarm Threshold - set points Audible and Visual Alarms at a value <1000 ppm or <25% LEL Note the PEL is 50 ppm thus alarm thresholds are typically in the range of 25 ppm",input:tb},
    {text:"Power Back up",input:tb},
    {text:"Continuous Ceiling Level Exhaust (~1 cfm/sq.ft.)",input:cb},
    {text:"Emergency Ventilation (~20 cfm/sq.ft.)",input:cb},
    {text:"Fan Key Control Outside of Room",input:cb},
    {text:"Emergency Pressure Control Automatic pressure relief cross over valve between high and low pressure zones (low pressure zone must safely contain the maximum pressure that can be achieved by interconnection Valve should automatically relieve excess system pressure to a lower pressure zone if the pressure in a high pressure zone rises to within 90 percent of the set point for emergency pressure relief devices. Pressure sensing device normally just upstream of valve.",input:tb},
    {text:"Machine Room Classification of Electrical Equipment (Class 1, Div2 or denergize all electrical eqt at =>25% LEL",input:tb},
    {text:"Machine Room Explosion Venting (Required for systems containing more than 600 lbs if in a sprinklered gas room)",input:tb},
    {text:"Machine Room Fire Protection (If installed, EH1 required, 55-2013, 6.10.2.2)",input:tb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
];
var allBatteryRoom = [
    {text:"Size and Location of Room (dimensions, area)",input:tb},
    {text:"Construction and fire resistance rating of room",input:tb},
    {text:"Description and Batteries (Electrolyte capacity for flooded lead-acid, nickel-cadmium and valve-regulated lead–acid (VRLA) batteries; Mass for for lithium-ion and lithium metal polymer batteries)",input:tb},
    {text:"Spill Control (Containment/Drainage) - (Required for free-flowing liquid electrolyte in individual vessels >  55 gal (208 L) or multiple vessels with an aggregate capacity > 1000 gal (3785 L),  1, 52.3.4.1)",input:cb},
    {text:"Smoke detection required",input:cb},
    {text:"Area/Room Fire Protection and Detection  ",input:tb},
    {text:"LEL Detection",input:cb},
    {text:"Ventilation (Required to limit Hydrogen to 1% of room volume or continuous at a rate of 1 ft3/min/ft2 (5.1 L/sec/m2) of floor area of the room or cabinet for flooded lead-acid, flooded nickel cadmium, and VRLA batteries, 1, 52.3.6)",input:tb},    
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
];
var allElectrical = [
    {text:"Maintain 3’ clear space around electrical equipment (greater clearance may be required for voltages over 600V)",input:tb},
    {text:"Annual Infrared inspections of critical equipment",input:cb},
    {text:"Visually inspection of the distribution switchgear annually",input:cb},
    {text:"LV MV & HV Air Circuit Breakers(>72kV) - Visually inspect and clean annually",input:cb},
    {text:"LV MV & HV Air Circuit Breakers(>72kV) - Trip test annually",input:cb},
    {text:"LV MV & HV Air Circuit Breakers(>72kV) - Contact resistance test every 3 years",input:cb},
    {text:"Motor Control Centers - Visually inspect/clean enclosure annually",input:cb},
    {text:"Motor Control Centers - Visually inspect wiring and insulators annually",input:cb},
    {text:"Motor Control Centers - Cycle annually",input:cb},
    {text:"Oil Filled Transformers - Conduct oil gas analysis Annually",input:cb},
    {text:"Oil Filled Transformers - Insulation resistance test every 3-5 years",input:cb},
    {text:"Oil Filled Transformers - Insulation power factor test every 3 to 5 years",input:cb},
    {text:"Oil Filled Transformers - Turns ratio test every 3-5 years",input:cb},
    {text:"Emergency Generator Load Testing  - Test monthly (min 30% of rating)",input:cb},
    {text:"Emergency Power Transfer Switches - Test monthly",input:cb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
];
var allExternalExposure = [
    {text:"External Exposure",input:tb},
    {text:"Idle Pallets <50 pallets – 20’; 50 to 200 pallets – 30’; >200 pallets – 50’ from buildings",input:tb},
    {text:"Large combustible trash containers At least 30’ and preferably 50’ from buildings",input:tb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
];
var allOilHeating = [
    {text:"Equipment Description",input:tb},
    {text:"Size and Location of Room (dimensions, area)",input:tb},
    {text:"Construction and fire resistance rating of room",input:tb},
    {text:"Type of Fluid and its properties(Petroleum based, water based, less hazardous)",input:tb},
    {text:"Operating Pressure and Temperature of Fluid",input:tb},
    {text:"Containment/Drainage (Emergency drainage systems shall be provided to direct/send liquid leakage and fire protection water to a safe location – 30, 17.10.1)",input:tb},
    {text:"System Capacity and Reservoir Size",input:tb},
    {text:"Piping & Joints (Welded, threaded welded ok for 2” and smaller - 30, 19.4.5.2",input:tb},
    {text:"Ventilation (Enclosed processing areas handling or using Class I liquids, or Class II or Class III liquids heated to temperatures at or above their flash points, shall be ventilated at a rate sufficient to maintain the concentration of vapors within the area at or below 25 percent of the lower flammable limit (LFL)- 30, 17.11.1.)",input:tb},
    {text:"Area/Room Fire Protection (EH1 - 30,19.4.6.1; EG-06-0020)",input:tb},
    {text:"Safety Interlocks to Shutdown system high temperature – 87, 8.16.3",input:cb},
    {text:"Safety Interlocks to Shutdown system Low reservoir level – 87, 9.4.5.4.2",input:cb},
    {text:"Safety Interlocks to Shutdown system Low flow limit – 87, 9.3.2",input:cb},
    {text:"Safety Interlocks to Shutdown system Sprinkler system water flow switches",input:cb},
    {text:"Safety Interlocks to Shutdown system heat detection",input:cb},
    {text:"Manual e-stop at least 40’ from equipment-87, 9.1.8",input:cb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
];
var allMiscStorage = [
    {text:"Location and Size of area (sq.ft.)",input:tb},
    {text:"Class I up to 12 feet – OH1, Class II up to 10 feet – OH1; up to 12 feet – OH2, Class III up to 12 feet – OH2, Class IV up to 10 feet – OH2, Class IV up (non-rack or BTB shelving)10  to 12 feet  - OH2, Group A plastics up to 5 feet - OH2",input:tb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
];
var allIdlePallet = [
    {text:"Location and Size of area (sq.ft.)",input:tb},
    {text:"Wood - Floor storage up to 6’: OH2 density is acceptable, limited to four stack piles with 8 ft aisles",input:cb},
    {text:"Wood - Floor storage over 6 feet requires much higher density (13, table 12.12.1.2.a)",input:cb},
    {text:"Wood - Rack storage of wood pallets requires high density (13, table 12.12.1.2.a)",input:cb},
    {text:"Plastic - Floor storage up to 4’: OH2 is acceptable, limited to two stack piles with 8 ft aisles",input:cb},
    {text:"Plastic - Storage over 4 feet require higher densities (13, 12.12.2.2.2.4)",input:cb},
    {text:"Plastic - Storage in racks requires ESFR protection (13, 12.12.2.3)",input:cb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
];
var allComputerRoom = [
    {text:"Equipment description, what is it used for?",input:tb},
    {text:"How many racks and how many rows?",input:tb},
    {text:"Critical to local opeartions or other global exterior operations",input:tb},
    {text:"Back up systems?",input:tb},
    {text:"Size and location of the room",input:tb},
    {text:"Construction and fire resistance",input:tb},
    {text:"Dropped ceiling",input:cb},
    {text:"Raised Floor",input:cb},
    {text:"Grade floor construction? concrete",input:tb},
    {text:"Raised floor panels? cast aluminum panels?",input:tb},
    {text:"Access to the room?",input:tb},
    {text:"Room protection - sprinklers, gas system, etc",input:tb},
    {text:"Detection, smoke, heat, etc?",input:tb},
    {text:"Protection and detection for the raised floor",input:tb},
    {text:"Fire extinguishers for the room? halon?",input:tb},
    {text:"Door and openings properly sealed?",input:cb},
    {text:"Combustibles kept to a minimum",input:cb},
    {text:"All penetrations sealed and no missing tiles?",input:cb},
    {text:"Door fan testing",input:tb},
    {text:"Back up power to the computer room, UPS or generator? for how long?",input:tb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
];
var allTesting = [
    {text:"Internal inspection of the sprinkler system piping is completed every 5 years (for obstructions)",input:cb},
    {text:"Weekly visual inspections of sprinkler valves",input:cb},
    {text:"Monthly visual inspections of sprinkler valves",input:cb},
    {text:"Mechanical waterflow devices (gongs) are tested quarterly",input:cb},
    {text:"Waterflow switches are tested semiannually",input:cb},
    {text:"Main drains are tested annually",input:cb},
    {text:"Annual partial trip test of dry pipe sprinklers",input:cb},
    {text:"Annual partial trip test of preaction sprinklers",input:cb},
    {text:"Full trip testing is completed every 3 years",input:cb},
    {text:"Annual full flow test of the deluge system",input:cb},
    {text:"Deluge and Preaction systems are tested every 3 years for air leakage",input:cb},
    {text:"Low air pressure alarms for dry Pipe, deluge & preaction systems are tested quarterly",input:cb},
    {text:"Deluge and preaction systems for freezers are internally inspected annually where the pipe enters the refrigerated area (ice plug inspection)",input:cb},
    {text:"Weekly churn testing of the fire pump",input:cb},
    {text:"Monthly churn testing of the fire pump",input:cb},
    {text:"Annual full flow testing of the fire pump",input:cb},
    {text:"The master pressure reducing valve (e.g. at the fire pump) is partially flow tested quarterly to move the valve from its seat",input:cb},
    {text:"Full flow testing of the master pressure reducing valve (e.g. at the fire pump) is completed annually",input:cb},
    {text:"Pressure reducing valve (e.g. at each floor) is partially flow tested annually to move the valve from its seat",input:cb},
    {text:"Full flow testing of pressure reducing valves is completed every 5-years",input:cb},
    {text:"The water supply tank is internally inspected every 5 years",input:cb},
    {text:"The water supply tank is internally inspected every 3 years (corrosion protection installed)",input:cb},
    {text:"Fire doors are tested annually",input:cb},
    {text:"The clean agent system is tested annually",input:cb},
    {text:"The clean agent system hoses are tested every 5-years",input:cb},
    {text:"The cylinders for the the clean agent system are inspected semiannually for agent quantity and pressure",input:cb},
    {text:"Initianing devices, alarm notification devices, and other fire alarms are tested annually",input:cb},
    {text:"Transmission of signals to off-premises location is tested annually",input:cb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
]
var dustCollector = [
    {text:"Description of Process What is being collected, etc - bag house, dust collector, cyclone",input:tb},
    {text:"Size and Location of Dust collector (dimensions, area)",input:tb},
    {text:"Construction and fire resistance rating of room",input:tb},
    {text:"Dust hazard analysis? for combustibility and how explosive it is, kst?",input:tb},
    {text:"Bonde and grounded for static electricity",input:tb},
    {text:"Sprinkler protection for the area",input:tb},
    {text:"Sprinkler protection for the dust collector",input:tb},
    {text:"Explosion isolation valves/dampers",input:tb},
    {text:"Explosion relief/venting panels",input:tb},
    {text:"Explosion suppression",input:tb},
    {text:"Spark arrestor",input:tb},
    {text:"Interlocks to shut down the fans or close the dampers",input:tb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
]
var combustionControlandAmmonia =[
    {text:"Flame failure detection, Pressure switch limits and interlocks, SSOV’s test annually",input:cb},
    {text:"Ammonia Refrigeration Vapor Detection Systems, Ventilation Systems tested annually",input:cb},
    {text:"Additional Comments",input:tb},
    {text:"Final Output",input:tb}
]